# Generated by Django 5.1.2 on 2024-11-05 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FacturasEndpoint', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagofactura',
            name='importe_pago',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True),
        ),
    ]
