# Generated by Django 5.1.2 on 2024-10-21 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EtiquetasSuministroModel',
            fields=[
                ('nombre_etiqueta', models.CharField(max_length=255)),
                ('color_etiqueta', models.CharField(blank=True, max_length=255, null=True)),
                ('id_etiqueta', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='SuministroModel',
            fields=[
                ('id_suministro', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('nombre_suministro', models.CharField(max_length=255)),
                ('geolocalizacion', models.CharField(blank=True, max_length=255, null=True)),
                ('domicilio', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SuministroEtiqueta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etiqueta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suministrosEndPoint.etiquetassuministromodel')),
                ('suministro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suministrosEndPoint.suministromodel')),
            ],
        ),
    ]
