# Generated by Django 5.1.2 on 2024-11-05 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suministrosEndPoint', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='suministromodel',
            name='nro_medidor',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='suministromodel',
            name='tarifa',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
